### ISSUE TITLE
Trading bot.

### ISSUE THREAD

**Issue by unknownjj** [noahtheprogrammer/merxbot#10]
Hi my friend, would I be able to please contact you for a small project? I really like your work and I was wondering if you could help make me a low latency trading bot for raydium (only manual buy/sell, no sniping). Of course will be paid. Let me know how I can contact you directly. Thanks a lot, and I really appreciate the work you do.

**Comment by nmweaver** [comment]
@unknownjj thank you for reaching out; I would be happy to help you complete your project! Feel free to reach out to me through my Discord. `bigweavers` is my username.

**Comment by FusionSwapDev** [comment]
hey man i tried to find you on discord but cant. would you mind to maybe share your TG if you have?

**Comment by nmweaver** [comment]
@unknownjj could you please resend that friend request? Discord removed it for some reason.

**Comment by unknownjj** [comment]
I sent you another friend request. Thanks.

**Comment by nmweaver** [comment]
Closing, as I am now in contact on Discord.
