### ISSUE TITLE
API support

### ISSUE THREAD

**Issue by simonpfeifhofer** [noahtheprogrammer/merxbot#15]
An HTTP-API (FastAPI would be an easy candidate) to support the commands /statistics, /stop, /resume.

**Comment by nmweaver** [comment]
Currently looking into the usage of Typer, which is FastAPI's little sibling designed for CLI programs.

**Comment by nmweaver** [comment]
Currently looking into a pull request that would remove the requirement for user input. Check out the currently active pull request for more information.

**Comment by nmweaver** [comment]
Pull request https://github.com/noahtheprogrammer/soltrade/pull/23 has now removed the need for this feature. Commands are no longer utilized in the program, and this issue has been resolved.
