### ISSUE TITLE
CCCAGG market does not exist for this coin pair (PRICKS-SOL)

### ISSUE THREAD

**Issue by studiozeroseven** [noahtheprogrammer/merxbot#25]
Not sure how to resolve this, is it with CryptoCompare API not having this pair listed?

**Comment by nordstageyt** [comment]
Did you find a solution?`

**Comment by studiozeroseven** [comment]
> Did you find a solution?`

No solution found, I think this more has to do with not having the data for a newish coin...

**Comment by nordstageyt** [comment]
We would need our own candle stick data generated. Perhaps find a different source of chart data.

**Comment by Smagia** [comment]
You can get data by changing the exchange code
(Possible from the new branch with the .env file)
