### ISSUE TITLE
Can you make a discord?

### ISSUE THREAD

**Issue by pillowtoaster** [noahtheprogrammer/merxbot#9]
Just found this project, and thought it would be easier to share new codes or trading ideas on discord 👍 If you create one please invite me ( :

**Comment by nmweaver** [comment]
Thank you for reaching out! I'll see if I can find someone to help me get a server set up if this suggestion receives more people requesting it.

**Comment by SVJA7IK** [comment]
Hi. Can you give your contact? Telegram?

**Comment by nmweaver** [comment]
@thefallentoaster We have finished polishing up our Discord server for community use! The link to join can be found [here.](https://discord.gg/WDS9Ya8KvX)
